---

- hosts: c2servers
  vars_files:
    - ../vars/redelk.yml
  gather_facts: false
  become: true
  tags: [teamservers]

  tasks:
    - name: Copying c2servers.tgz
      copy:
        src: /tmp/redelk_latest/c2servers.tgz
        dest: /tmp
      tags: [teamserver_copy]

    - name: Extracting teamserver.tgz
      shell: mkdir -p /tmp/c2servers && tar -zxvf /tmp/c2servers.tgz -C /tmp/c2servers --strip-components=1
      args:
        warn: false
      tags: [c2servers_extract]

    - name: Installing Cobaltstrike Teamserver package
      command:
        cmd: ./install-c2server-cobaltstrike.sh {{ hostvars[inventory_hostname]['filebeat_id'] }} {{ scenario_name }} {{ redelk_server_host }}:{{ redelk_server_port }}
        chdir: /tmp/c2servers
      register: install_output
      ignore_errors: true
      tags: [c2servers_install]

    - name: Checking for failures
      fail:
        msg: "Error occurred. Check /tmp/c2servers/redelk-install.log for details."
      when: '"ERROR" in install_output.stdout'
      tags: [c2servers_install]